<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Sun, 16 Sep 2012 00:58:28 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'addon_simularfrete' => 
  array (
    'is_setup' => '1',
    'tipos' => 
    array (
      0 => 'pac',
      1 => 'esedex',
      2 => 'acobrar',
      3 => 'sedex',
    ),
  ),
  'addon_parcelas' => 
  array (
    'is_setup' => '1',
    'tipos' => 
    array (
      0 => 'deposito',
      1 => 'cheque',
      2 => 'boleto',
      3 => 'pagseguro',
      4 => 'pagdigital',
      5 => 'moip',
      6 => 'zCielo',
      7 => 'shopline',
    ),
    'rodape1' => 'deposito',
    'rodape2' => 'pagseguro',
    'descboleto' => '0',
    'scroll' => 'html',
    'scrolln' => '10',
    'pdf' => 'sim',
    'twitter' => 'nao',
    'usertwitter' => 'googlebrasil',
  ),
);
