<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Mon, 20 Aug 2012 23:12:19 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_boletobradesco' => 
  array (
    'is_setup' => '1',
  ),
  'checkout_boletobancodobrasil' => 
  array (
    'is_setup' => '1',
  ),
  'checkout_boletoitau' => 
  array (
    'is_setup' => '1',
  ),
  'checkout_deposito' => 
  array (
    'is_setup' => '1',
  ),
  'checkout_pagseguro' => 
  array (
    'is_setup' => '1',
  ),
);
