<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Tue, 11 Sep 2012 03:56:49 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_boletobradesco' => 
  array (
    'is_setup' => '1',
    'availablecountries' => 'all',
    'boletobradescocedente' => '3423',
    'boletobradescoagencia' => '324234',
    'boletobradescoagenciadv' => '0',
    'boletobradescoconta' => '324234',
    'boletobradescocontadv' => '0',
    'boletobradescocarteira' => '06',
    'demoum' => 'REFERENTE A COMPRAS ONLINE',
    'demodois' => 'Duvidas e sugest&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;otilde;es entre em contato conosco:',
    'demotres' => 'sac@seusite.com.br | +55 xx 0000.0000',
    'boletobradescoinstrucaoum' => 'Multa de R$ 3,00 por atraso.',
    'boletobradescoinstrucaodois' => 'Apos o vencimento, pagavel apenas no Banco Real',
    'boletobradescoinstrucaotres' => 'Fatura sujeita a protesto no SPC/SERASA',
    'boletobradescoinstrucaoquatro' => 'Juros de mora de 0,1% ao dia.',
    'boletobradescoaceite' => '',
    'boletobradescoespeciedoc' => 'DS',
    'boletobradescoespecie' => 'R$',
    'boletobradescocpfcnpj' => '',
    'boletobradescodiasparavencimento' => '10',
    'postagem' => '%%GLOBAL_ShopPath%%/modules/checkout/boletobradesco/boleto_bradesco.php?boleto=',
    'imagems' => '%%GLOBAL_ShopPath%%/modules/checkout/boletobradesco/images/logo.gif',
    'helptext' => 'Voc&ecirc; escolheu pagar com Boleto Banc&aacute;rio do Banco Bradesco.
Para reimprimir seu boleto clique no bot&atilde;o abaixo.<br>',
  ),
  'checkout_boletobancodobrasil' => 
  array (
    'is_setup' => '1',
    'availablecountries' => 'all',
    'boletobancodobrasilcedente' => '4234',
    'boletobancodobrasilagencia' => '24234',
    'boletobancodobrasilconta' => '43',
    'boletobancodobrasilcarteira' => '18',
    'boletobancodobrasilconvenio' => '0000000',
    'boletobancodobrasilcontrato' => '0000000',
    'boletobancodobrasilvariacaocarteira' => '-019',
    'boletobancodobrasilformatacaoconvenio' => '7',
    'boletobancodobrasilformatacaonossonumero' => '7',
    'demoum' => 'REFERENTE A COMPRAS ONLINE',
    'demodois' => 'Duvidas e sugest&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;otilde;es entre em contato conosco:',
    'demotres' => 'sac@seusite.com.br | +55 xx 0000.0000',
    'boletobancodobrasilinstrucaoum' => 'Multa de R$ 3,00 por atraso.',
    'boletobancodobrasilinstrucaodois' => 'Apos o vencimento, pagavel apenas no Banco Real',
    'boletobancodobrasilinstrucaotres' => 'Fatura sujeita a protesto no SPC/SERASA',
    'boletobancodobrasilinstrucaoquatro' => 'Juros de mora de 0,1% ao dia.',
    'boletobancodobrasilaceite' => 'N',
    'boletobancodobrasilespeciedoc' => 'DS',
    'boletobancodobrasilespecie' => 'R$',
    'boletobancodobrasilcpfcnpj' => '',
    'boletobancodobrasildiasparavencimento' => '10',
    'postagem' => '%%GLOBAL_ShopPath%%/modules/checkout/boletobancodobrasil/boleto_bancodobrasil.php?boleto=',
    'imagems' => '%%GLOBAL_ShopPath%%/modules/checkout/boletobancodobrasil/images/logo.gif',
    'helptext' => 'Voc&ecirc; escolheu pagar com Boleto Banc&aacute;rio do Banco do Brasil.
Para reimprimir seu boleto clique no bot&atilde;o abaixo.<br>',
  ),
  'checkout_boletoitau' => 
  array (
    'is_setup' => '1',
    'availablecountries' => 'all',
    'desconto' => '0',
    'boletoitaucedente' => '32423',
    'boletoitauagencia' => '234',
    'boletoitauconta' => '234',
    'boletoitaucarteira' => '175',
    'demoum' => 'REFERENTE A COMPRAS ONLINE',
    'demodois' => 'Duvidas e sugest&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;otilde;es entre em contato conosco:',
    'demotres' => 'sac@seusite.com.br | +55 xx 0000.0000',
    'boletoitauinstrucaoum' => 'Multa de R$ 3,00 por atraso.',
    'boletoitauinstrucaodois' => 'Apos o vencimento, pagavel apenas no Banco Real',
    'boletoitauinstrucaotres' => 'Fatura sujeita a protesto no SPC/SERASA',
    'boletoitauinstrucaoquatro' => 'Juros de mora de 0,1% ao dia.',
    'boletoitauaceite' => '',
    'boletoitauespeciedoc' => '',
    'boletoitauespecie' => 'R$',
    'boletoitaucpfcnpj' => '',
    'boletoitaudiasparavencimento' => '10',
    'boletoitaudv' => '0',
    'postagem' => '%%GLOBAL_ShopPath%%/modules/checkout/boletoitau/boleto_itau.php?boleto=',
    'imagems' => '%%GLOBAL_ShopPath%%/modules/checkout/boletoitau/images/logo.gif',
    'helptext' => 'Voc&ecirc; escolheu pagar com Boleto Banc&aacute;rio do Banco Ita&uacute;.
Para reimprimir seu boleto clique no bot&atilde;o abaixo.<br>',
  ),
  'checkout_cielo' => 
  array (
    'is_setup' => '1',
    'serial' => '102030',
    'displayname' => 'Cartoes de Credito Visa e Master',
    'availablecountries' => 
    array (
      0 => 'all',
      1 => '30',
    ),
    'modo' => 'T',
    'afiliacao' => '1001734898',
    'chave' => 'e84827130b9837473681c2787007da5914d6359947015a5cdb2b8843db0fa832',
    'loja' => 'Loja de Teste',
    'meios' => 
    array (
      0 => 'V',
      1 => 'M',
      2 => 'E',
      3 => 'EL',
      4 => 'DIN',
      5 => 'DIS',
      6 => 'AM',
    ),
    'parcelamin' => '5.00',
    'juros' => '1.00',
    'desconto' => '5.00',
    'div' => '12',
    'jurosde' => '3',
    'tipojuros' => '2',
  ),
  'checkout_deposito' => 
  array (
    'is_setup' => '1',
    'displayname' => 'Deposito Bancario',
    'availablecountries' => 'all',
    'desconto' => '0',
    'helptext' => 'Banco: Banco do Brasil
Agencia: 64646
Nome: John Smith
Conta: XXXXXXXXXXXX

Mais Instrucoes e Detalhes.',
  ),
  'checkout_pagseguro' => 
  array (
    'is_setup' => '1',
    'displayname' => 'PagSeguro',
    'availablecountries' => 'all',
    'pagemail' => '234',
    'token' => '0',
    'acrecimo' => '0.00',
    'jurosde' => '0',
    'helptext' => '<a href="javascript:window.open(\'%%GLOBAL_ShopPath%%/modules/checkout/pagseguro/repagar.php?pedido=%%GLOBAL_OrderId%%\',\'popup\',\'width=800,height=800,scrollbars=yes\');void(0);"><img src=\'%%GLOBAL_ShopPath%%/modules/checkout/pagseguro/images/final.gif\' border=\'0\'></a>
<br>',
    'htmlpagseguro' => '324',
  ),
);
