<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Sun, 09 Sep 2012 00:08:28 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_deposito' => 
  array (
    'is_setup' => '1',
    'displayname' => 'Deposito Bancario',
    'availablecountries' => 'all',
    'desconto' => '0',
    'helptext' => 'Banco: Banco do Brasil
Agencia: 64646
Nome: John Smith
Conta: XXXXXXXXXXXX

Mais Instrucoes e Detalhes.',
  ),
  'checkout_pagseguro' => 
  array (
    'is_setup' => '1',
    'displayname' => 'PagSeguro',
    'availablecountries' => 'all',
    'pagemail' => 'abc@teste.com',
    'token' => '0',
    'acrecimo' => '0.00',
    'jurosde' => '0',
    'helptext' => '<a href="javascript:window.open(\'%%GLOBAL_ShopPath%%/modules/checkout/pagseguro/repagar.php?pedido=%%GLOBAL_OrderId%%\',\'popup\',\'width=800,height=800,scrollbars=yes\');void(0);"><img src=\'%%GLOBAL_ShopPath%%/modules/checkout/pagseguro/images/final.gif\' border=\'0\'></a>
<br>',
    'htmlpagseguro' => 'dfsdfds',
  ),
);
