<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Mon, 20 Aug 2012 23:08:33 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'currencyid' => '1',
    'currencycountryid' => '30',
    'currencycouregid' => NULL,
    'currencycode' => 'BRL',
    'currencyconvertercode' => NULL,
    'currencyname' => 'Default Currency',
    'currencyexchangerate' => '1.0000000000',
    'currencystring' => 'R$',
    'currencystringposition' => 'LEFT',
    'currencydecimalstring' => ',',
    'currencythousandstring' => '.',
    'currencydecimalplace' => '2',
    'currencylastupdated' => '1345504113',
    'currencyisdefault' => '1',
    'currencystatus' => '1',
  ),
  'default' => '1',
);
