<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Tue, 21 Aug 2012 03:34:18 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    4 => 
    array (
      'pagetitle' => 'Quem Somos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '4',
      'pagecustomersonly' => '0',
    ),
    5 => 
    array (
      'pagetitle' => 'Horário de Atendimento',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '5',
      'pagecustomersonly' => '0',
    ),
    3 => 
    array (
      'pagetitle' => 'Contato',
      'pagetype' => '3',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '3',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);
