<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Sat, 25 Aug 2012 21:38:26 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    3 => 
    array (
      'categoryid' => '3',
      'catparentid' => '0',
      'catname' => 'Coleiras ',
      'catdepth' => '0',
    ),
    2 => 
    array (
      'categoryid' => '2',
      'catparentid' => '0',
      'catname' => 'Camas ',
      'catdepth' => '0',
    ),
    13 => 
    array (
      'categoryid' => '13',
      'catparentid' => '0',
      'catname' => 'Roupas',
      'catdepth' => '0',
    ),
    16 => 
    array (
      'categoryid' => '16',
      'catparentid' => '0',
      'catname' => 'Calcinhas Com Babado',
      'catdepth' => '0',
    ),
    12 => 
    array (
      'categoryid' => '12',
      'catparentid' => '0',
      'catname' => 'Acessórios',
      'catdepth' => '0',
    ),
    18 => 
    array (
      'categoryid' => '18',
      'catparentid' => '0',
      'catname' => 'Gatos',
      'catdepth' => '0',
    ),
  ),
  2 => 
  array (
    11 => 
    array (
      'categoryid' => '11',
      'catparentid' => '2',
      'catname' => 'Camas europa nylon',
      'catdepth' => '1',
    ),
    26 => 
    array (
      'categoryid' => '26',
      'catparentid' => '2',
      'catname' => 'Camas Túnel 3 em 1',
      'catdepth' => '1',
    ),
    9 => 
    array (
      'categoryid' => '9',
      'catparentid' => '2',
      'catname' => 'Camas fofinhas',
      'catdepth' => '1',
    ),
    10 => 
    array (
      'categoryid' => '10',
      'catparentid' => '2',
      'catname' => 'Camas Igloo',
      'catdepth' => '1',
    ),
  ),
  13 => 
  array (
    20 => 
    array (
      'categoryid' => '20',
      'catparentid' => '13',
      'catname' => 'Vestidos',
      'catdepth' => '1',
    ),
    21 => 
    array (
      'categoryid' => '21',
      'catparentid' => '13',
      'catname' => 'Capas de Chuva',
      'catdepth' => '1',
    ),
    22 => 
    array (
      'categoryid' => '22',
      'catparentid' => '13',
      'catname' => 'Uniformes',
      'catdepth' => '1',
    ),
    23 => 
    array (
      'categoryid' => '23',
      'catparentid' => '13',
      'catname' => 'Regata',
      'catdepth' => '1',
    ),
    24 => 
    array (
      'categoryid' => '24',
      'catparentid' => '13',
      'catname' => 'Macacão',
      'catdepth' => '1',
    ),
  ),
  12 => 
  array (
    28 => 
    array (
      'categoryid' => '28',
      'catparentid' => '12',
      'catname' => 'Bolsa Canguru',
      'catdepth' => '1',
    ),
    25 => 
    array (
      'categoryid' => '25',
      'catparentid' => '12',
      'catname' => 'Bolsa Transporte',
      'catdepth' => '1',
    ),
    27 => 
    array (
      'categoryid' => '27',
      'catparentid' => '12',
      'catname' => 'Caixa Transporte',
      'catdepth' => '1',
    ),
    29 => 
    array (
      'categoryid' => '29',
      'catparentid' => '12',
      'catname' => 'Guias',
      'catdepth' => '1',
    ),
    14 => 
    array (
      'categoryid' => '14',
      'catparentid' => '12',
      'catname' => 'Boné',
      'catdepth' => '1',
    ),
    15 => 
    array (
      'categoryid' => '15',
      'catparentid' => '12',
      'catname' => 'Edredom / Cobertores',
      'catdepth' => '1',
    ),
    17 => 
    array (
      'categoryid' => '17',
      'catparentid' => '12',
      'catname' => 'Colchonete',
      'catdepth' => '1',
    ),
  ),
  29 => 
  array (
    30 => 
    array (
      'categoryid' => '30',
      'catparentid' => '29',
      'catname' => 'Guia Saia ',
      'catdepth' => '2',
    ),
  ),
  18 => 
  array (
    19 => 
    array (
      'categoryid' => '19',
      'catparentid' => '18',
      'catname' => 'Coleiras',
      'catdepth' => '1',
    ),
  ),
);
